# localization_data.py

texts = {
    'en': {
        'title': 'ADB Toolkit',
        'switch_lang': 'Switch to Russian',
        'device_list': 'Device List',
        'list_packages': 'List Packages',
        'view_logcat': 'View Logcat',
        'network_info': 'Network Info',
        'running_processes': 'Running Processes',
        'app_permissions': 'App Permissions',
        'extended_info': 'Extended Device Info',
        'ok': 'OK',
        'cancel': 'Cancel',
        'input_title': 'Input Required',
        'input_prompt': 'Please enter value:',
        'output_title': 'Command Output',
        'no_device': 'No device connected.',
        'error': 'Error',
        'success': 'Success',
        'adb_not_found': 'ADB not found. Please ensure ADB is installed and in your PATH.',
        'select_device': 'Select a device:',
        'operation_complete': 'Operation completed successfully.',
        'operation_failed': 'Operation failed.',
        'confirm': 'Confirm',
        'yes': 'Yes',
        'no': 'No',
        'check_device': 'Check Device',
        'launch_scrcpy': 'Launch Scrcpy',
        'get_network_info': 'Get Network Info',
        'extended_device_info': 'Extended Device Info',
        'tcp_connect_wifi': 'TCP Connect over WiFi',
        'tcp_disconnect': 'TCP Disconnect',
        'device': 'Device',
        'file_management': 'File Management',
        'install_apk': 'Install APK',
        'browse_files': 'Browse Files',
        'pull_file': 'Pull File from Device',
        'push_file': 'Push File to Device',
        'actions': 'Actions',
        'send_message': 'Send Message',
        'take_screenshot': 'Take Screenshot',
        'screenshare': 'Screenshare',
        'front_camera_preview': 'Front Camera Preview',
        'rear_camera_preview': 'Rear Camera Preview',
        'extract_contacts': 'Extract Contacts',
        'extract_gallery_images': 'Extract Gallery Images',
        'battery_info': 'Battery Info',
        'launch_app_by_package': 'Launch App by Package',
        'lock_screen': 'Lock Screen',
        'reboot_device': 'Reboot Device',
        'power_off': 'Power Off',
        'list_running_processes': 'List Running Processes',
        'start_app_activity': 'Start App Activity',
        'open_url_in_browser': 'Open URL in Browser',
        'input_text_to_device': 'Input Text to Device',
        'simulate_tap': 'Simulate Tap',
        'simulate_swipe': 'Simulate Swipe',
        'list_installed_packages': 'List Installed Packages',
        'uninstall_app_by_package': 'Uninstall App by Package',
        'show_logcat': 'Show Logcat',
        'toggle_wifi': 'Toggle WiFi',
        'toggle_mobile_data': 'Toggle Mobile Data',
        'permissions': 'Permissions',
        'view_app_permissions': 'View App Permissions',
        'grant_app_permission': 'Grant App Permission',
        'revoke_app_permission': 'Revoke App Permission',
        'terminal': 'Terminal',
        'open_android_terminal': 'Open Android Terminal',
        'language': 'Language',
        'stream_rear_camera': 'Stream Rear Camera',
        'stream_front_camera': 'Stream Front Camera',
        'camera': 'Camera',
    },
    'ru': {
        'title': 'ADB Инструментарий',
        'switch_lang': 'Переключить на английский',
        'device_list': 'Список устройств',
        'list_packages': 'Список пакетов',
        'view_logcat': 'Просмотр Logcat',
        'network_info': 'Сетевые данные',
        'running_processes': 'Запущенные процессы',
        'app_permissions': 'Разрешения приложений',
        'extended_info': 'Расширенная информация',
        'ok': 'ОК',
        'cancel': 'Отмена',
        'input_title': 'Требуется ввод',
        'input_prompt': 'Пожалуйста, введите значение:',
        'output_title': 'Результат команды',
        'no_device': 'Устройство не подключено.',
        'error': 'Ошибка',
        'success': 'Успех',
        'adb_not_found': 'ADB не найден. Пожалуйста, убедитесь, что ADB установлен и добавлен в PATH.',
        'select_device': 'Выберите устройство:',
        'operation_complete': 'Операция успешно завершена.',
        'operation_failed': 'Операция не удалась.',
        'confirm': 'Подтвердить',
        'yes': 'Да',
        'no': 'Нет',
        'check_device': 'Проверить устройство',
        'launch_scrcpy': 'Запустить Scrcpy',
        'get_network_info': 'Сетевые данные',
        'extended_device_info': 'Расширенная информация',
        'tcp_connect_wifi': 'TCP-подключение по WiFi',
        'tcp_disconnect': 'TCP-отключение',
        'device': 'Устройство',
        'file_management': 'Файлы',
        'install_apk': 'Установить APK',
        'browse_files': 'Обзор файлов',
        'pull_file': 'Скачать файл с устройства',
        'push_file': 'Загрузить файл на устройство',
        'actions': 'Действия',
        'send_message': 'Отправить сообщение',
        'take_screenshot': 'Скриншот',
        'screenshare': 'Трансляция экрана',
        'front_camera_preview': 'Просмотр с фронтальной камеры',
        'rear_camera_preview': 'Просмотр с задней камеры',
        'extract_contacts': 'Извлечь контакты',
        'extract_gallery_images': 'Извлечь изображения галереи',
        'battery_info': 'Информация о батарее',
        'launch_app_by_package': 'Запуск приложения по пакету',
        'lock_screen': 'Заблокировать экран',
        'reboot_device': 'Перезагрузить устройство',
        'power_off': 'Выключить',
        'list_running_processes': 'Список процессов',
        'start_app_activity': 'Запустить активити',
        'open_url_in_browser': 'Открыть URL в браузере',
        'input_text_to_device': 'Ввод текста на устройстве',
        'simulate_tap': 'Симулировать нажатие',
        'simulate_swipe': 'Симулировать свайп',
        'list_installed_packages': 'Список установленных пакетов',
        'uninstall_app_by_package': 'Удалить приложение по пакету',
        'show_logcat': 'Показать Logcat',
        'toggle_wifi': 'Включить/выключить WiFi',
        'toggle_mobile_data': 'Включить/выключить мобильные данные',
        'permissions': 'Разрешения',
        'view_app_permissions': 'Просмотр разрешений',
        'grant_app_permission': 'Выдать разрешение',
        'revoke_app_permission': 'Отозвать разрешение',
        'terminal': 'Терминал',
        'open_android_terminal': 'Открыть Android терминал',
        'language': 'Язык',
        'stream_rear_camera': 'Потоковая передача данных с задней камеры',
        'stream_front_camera': 'Потоковая передняя камера',
        'camera': 'Камера',
    }
} 